/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lt_so_Create */

#ifndef _Included_com_lt_so_Create
#define _Included_com_lt_so_Create
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lt_so_Create
 * Method:    helloFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_lt_so_Create_helloFromC
  (JNIEnv *, jclass);

/*
 * Class:     com_lt_so_Create
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_lt_so_Create_add
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
